# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_number', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=250)),
                ('city_town', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AreaZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('areas_covered', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AreaZoneRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assumed', models.DateField(verbose_name='Date of assumption of role')),
                ('date_left', models.DateField(verbose_name='Date of leaving role')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info_type_name', models.CharField(max_length=100)),
                ('contact_info_type_code', models.CharField(max_length=10)),
                ('contact_info_type_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mission', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentalMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.Department')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scheduled', models.DateField()),
                ('follow_up_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_mode_name', models.CharField(max_length=100)),
                ('follow_up_mode_code', models.CharField(max_length=5)),
                ('follow_up_mode_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateField()),
                ('requests_needs_of_person', models.TextField()),
                ('ministry_given', models.TextField()),
                ('home_group_invitation', models.TextField()),
                ('thursday_invitation', models.TextField()),
                ('sunday_invitation', models.TextField()),
                ('next_action', models.TextField()),
                ('date_of_next_action', models.DateTimeField()),
                ('follow_up_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.FollowUp')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_status_name', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type_name', models.CharField(max_length=100)),
                ('follow_up_type_description', models.TextField()),
                ('follow_up_type_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='HomegroupRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assumed', models.DateField(verbose_name='Date of assumption of role')),
                ('date_left', models.DateField(verbose_name='Date of leaving role')),
            ],
        ),
        migrations.CreateModel(
            name='HomegroupVenues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homegroup_name', models.CharField(max_length=250)),
                ('meeting_day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.Addresses')),
                ('area_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.AreaZone')),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status_name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('salutation', models.CharField(max_length=10)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=5)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('age_group', models.CharField(max_length=20)),
                ('place_of_birth', models.CharField(max_length=150)),
                ('date_of_ftv', models.DateField(verbose_name='Date of first time visit')),
                ('referrer', models.OneToOneField(blank='true', null='true', on_delete=django.db.models.deletion.CASCADE, to='vip.PersonalDetails')),
            ],
        ),
        migrations.CreateModel(
            name='PersonsAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateField(verbose_name='Date of Entrance')),
                ('date_of_leaving', models.DateField(verbose_name='Date of Leaving')),
                ('used_for', models.CharField(max_length=20)),
                ('addresses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vip.Addresses')),
                ('personal_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vip.PersonalDetails')),
            ],
        ),
        migrations.CreateModel(
            name='PersonsMaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('marital_status_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.MaritalStatus')),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.PersonalDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('ministry_outline', models.TextField()),
                ('parent_role', models.OneToOneField(blank='true', null='true', on_delete=django.db.models.deletion.CASCADE, to='vip.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Spirituals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spirituals_name', models.CharField(max_length=200)),
                ('spirituals_status', models.CharField(max_length=20)),
                ('date_spirituals_received', models.DateField()),
                ('where_spirituals_received', models.CharField(max_length=250)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.PersonalDetails')),
            ],
        ),
        migrations.CreateModel(
            name='SpiritualsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('scripture_reference', models.TextField()),
                ('howto', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='spirituals',
            name='spirituals_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.SpiritualsType'),
        ),
        migrations.AddField(
            model_name='homegrouproles',
            name='homegroup_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.HomegroupVenues'),
        ),
        migrations.AddField(
            model_name='homegrouproles',
            name='personal_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='homegrouproles',
            name='role_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.Roles'),
        ),
        migrations.AddField(
            model_name='followupoutcomes',
            name='follow_up_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.FollowUpStatus'),
        ),
        migrations.AddField(
            model_name='followupoutcomes',
            name='person_following_up_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='followup',
            name='follow_up_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.FollowUpMode'),
        ),
        migrations.AddField(
            model_name='followup',
            name='follow_up_type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.FollowUpType'),
        ),
        migrations.AddField(
            model_name='followup',
            name='person_being_followed_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciple', to='vip.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='followup',
            name='person_following_up_scheduled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipler', to='vip.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='departmentalmembership',
            name='personal_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='departmentalmembership',
            name='role_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.Roles'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_info_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.ContactInfoType'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='personal_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='areazoneroles',
            name='personal_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='areazoneroles',
            name='role_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.Roles'),
        ),
        migrations.AddField(
            model_name='areazoneroles',
            name='zone_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.AreaZone'),
        ),
    ]
