# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-30 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(max_length=100)),
                ('skills_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_category_name', models.CharField(max_length=100)),
                ('skills_category_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.SkillsCategory'),
        ),
    ]
